.travis.yml
MANIFEST.in
example/app.py
invenio_db/cli.py
invenio_db/core.py
setup.py
tests/test_db.py

tests: full cli coverage

---

.travis.yml
CHANGES.rst
RELEASE-NOTES.rst
invenio_db/version.py

Invenio-DB v1.0.0a1

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_db/version.py

Invenio-DB v1.0.0a3

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_db/version.py

Invenio-DB v1.0.0a4

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_db/version.py

Invenio-DB v1.0.0a6

---

invenio_db/cli.py

* BETTER Checks database existence when doing `db init`. (closes #15)
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>

cli: check database existence during init

---

AUTHORS.rst
CHANGES.rst
RELEASE-NOTES.rst
invenio_db/version.py

Signed-off-by: Tibor Simko <tibor.simko@cern.ch>

release: v1.0.0a7

---

invenio_db/version.py

Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>

version: post-release bump

---

.travis.yml
docs/usage.rst
invenio_db/cli.py
invenio_db/core.py
setup.py
tests/conftest.py
tests/demo/versioned_a.py
tests/demo/versioned_b.py
tests/test_db.py
tests/test_versioning.py

* Adds SQLAlchemy-Continuum for versioning support.  (closes #24)
Co-authored-by: Jiri Kuncar <jiri.kuncar@cern.ch>
Signed-off-by: Sami Hiltunen <sami.mikael.hiltunen@cern.ch>

global: addition of versioning support

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_db/core.py
invenio_db/version.py
tests/test_versioning.py

release: v1.0.0a8

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_db/version.py

release: v1.0.0a9

---

run-tests.sh
setup.py

* Replaces pep257 with pydocstyle.
Signed-off-by: Sami Hiltunen <sami.mikael.hiltunen@cern.ch>

installation: pydocstyle>=1.0.0

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_db/version.py

Signed-off-by: Tibor Simko <tibor.simko@cern.ch>

release: v1.0.0a10

---

.travis.yml
docs/api.rst
setup.py

installation: testing support for PyPy

---

CHANGES.rst
RELEASE-NOTES.rst
docs/conf.py
invenio_db/shared.py
invenio_db/version.py

release: v1.0.0b1

---

docs/conf.py
tests/test_examples_app.py

* Adds test_example_app.py. (closes #50)
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>

tests: addition of test_example_app.py

---

INSTALL.rst
MANIFEST.in
README.rst
RELEASE-NOTES.rst
docs/requirements.txt

Signed-off-by: Tibor Simko <tibor.simko@cern.ch>

docs: move to readthedocs.io

---

invenio_db/__init__.py
invenio_db/alembic/96e796392533_create_database_migrations.py
invenio_db/alembic/dbdbc1b19cf2_create_transaction_table.py
invenio_db/alembic/script.py.mako
invenio_db/ext.py
setup.py
tests/test_db.py
tests/test_versioning.py

Related PRs:
- https://github.com/inveniosoftware/invenio-accounts/pull/172
- https://github.com/inveniosoftware/invenio-records/pull/158
- https://github.com/inveniosoftware/invenio-communities/pull/89
- https://github.com/inveniosoftware/invenio-pidstore/pull/93
- https://github.com/inveniosoftware/invenio-files-rest/pull/133

ext: initial alembic support

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_db/version.py

release: v1.0.0b3

---

invenio_db/shared.py
setup.py

I am working on an Alembic recipe that checks naming convention.

shared: addition of default naming convention

---

invenio_db/alembic/35c1075e6360_force_naming_convention.py
invenio_db/alembic/96e796392533_create_database_migrations.py
invenio_db/alembic/dbdbc1b19cf2_create_transaction_table.py
pytest.ini
tests/conftest.py
tests/test_db.py
tests/test_versioning.py

It includes a proposal for an upgrade recipe that should change names (recreate) indexes and constraints.

alembic: recipe forcing naming convention

---

.editorconfig
.gitignore
.travis.yml
CONTRIBUTING.rst
MANIFEST.in
docs/Makefile
docs/conf.py
docs/examplesapp.rst
docs/make.bat
setup.py
tests/test_examples_app.py

* FIX Adds changes according to release preparation checklist.
Signed-off-by: Paulina Lach <paulina.malgorzata.lach@cern.ch>

global: release checklist

---

invenio_db/shared.py
invenio_db/utils.py
setup.py
tests/test_utils.py

utils: function for rebuilding encrypted fields

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_db/version.py

release: 1.0.0b4

---

INSTALL.rst
docs/configuration.rst
docs/index.rst
invenio_db/__init__.py

docs: configuration defaults and better usage

---

.lgtm
.travis.yml
README.rst
RELEASE-NOTES.rst
requirements-devel.txt

* Removes PyPy from Travis test matrix.
* Removes experimental warning note.

global: release fixes

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_db/version.py

This is needed in order to merge pull requests in other modules.
Signed-off-by: Nicolas Harraudeau <nicolas.harraudeau@cern.ch>

release: v1.0.0b6

---

INSTALL.rst
docs/examplesapp.rst
examples/app.py

- ADDS dependencies in INSTALL.rst
- FIX in example/app.py for sphinx rendering

docs: addition of dependencies and example app fix

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_db/version.py

release: v1.0.0b8

---

setup.py
tests/test_utils.py

* Bumped version of psycopg2 because of this issue: https://github.com/psycopg/psycopg2/issues/594
and of cryptography because of this: https://github.com/pyca/pyopenssl/issues/728
(Closes https://github.com/inveniosoftware/invenio-db/issues/103)

tests: fix import from sqlalchemy_utils

---

.travis.yml
setup.py

global: pin pytest version, ignore travis error for sqlalchemy

---

.travis.yml
README.rst
setup.py

travis: add postgresql 10 test

---

setup.py

installation: unpin sqlalchemy-continuum

---

CHANGES.rst
invenio_db/version.py

release: v1.0.4

---

.github/workflows/tests.yml
CONTRIBUTING.rst
MANIFEST.in
README.rst
run-tests.sh
setup.py

ci: migrate to GA

---

setup.py

closes https://github.com/inveniosoftware/invenio-db/issues/147

Change requirements for SQLAlchemy

---

invenio_db/ext.py
setup.py
tests/test_db.py
tests/test_versioning.py

* Replaces `pkg_resources` with `importlib_metadata` and
`importlib_resources`.

ext: replace pkg_resources

---

.github/workflows/tests.yml
constraints-min.txt
constraints-pypi.txt
invenio_db/alembic/35c1075e6360_force_naming_convention.py
invenio_db/cli.py
invenio_db/ext.py
invenio_db/shared.py
invenio_db/utils.py
setup.py
tests/test_db.py
tests/test_utils.py

* Adds support for SQLAlchemy 1.4, Flask-SQLAlchemy 2.5 and Flask 2.1.
(closes #147)

installation: support SQLAlchemy 1.4 and Flask 2.1

---

invenio_db/uow.py

* closes https://github.com/CERNDocumentServer/cds-rdm/issues/193

uow: improve decorator to create uow if it's None
