INSTALL.rst, invenio_db/__init__.py
* Adds two sections on usage of models and entry points.
* Adds reference to Flask-SQLAlchemy documentation.
Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>
=> docs: usage guide additions

invenio_db/core.py
* Fixes issue when passing kwargs to contructor and app is set to None.
(closes #5)
=> core: fix for passing kwargs to constructor

invenio_db/cli.py, tests/test_db.py
* Fixes issue with tables not being created in correct order with respect to foreign key constraints.
Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>
=> cli: table creation order fix

CHANGES.rst, invenio_db/cli.py, invenio_db/version.py, tests/test_db.py
=> Invenio-DB v1.0.0a2

invenio_db/shared.py
* Fixes issue with transtaction insolation level by applying a driver
hack for SQLite engine.
=> sqlite: fix transaction isolation level

invenio_db/core.py
* Forces orm mapper configuration after all models are loaded in order
to load mapper extensions like SQLAlchemy-Continuum.
=> core: automatic orm mapper configuration

invenio_db/core.py, tests/test_db.py
* Renames entrypoint_name parameter to entry_point_group to follow
conventions in other modules.
Signed-off-by: Sami Hiltunen <sami.mikael.hiltunen@cern.ch>
=> global: entrypoint_name parameter renaming

invenio_db/shared.py, tests/test_db.py
* Enables foreign key constraint checking for SQLite.
Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>
=> sqlite: foreign key constraint checking

invenio_db/shared.py, tests/test_db.py
* Adds ``LocalProxy`` adapter for SQLite and PostgreSQL.  (closes #33)
=> global: support for LocalProxy objects

.editorconfig, .travis.yml, docs/api.rst, docs/conf.py, docs/index.rst, example/app.py, invenio_db/__init__.py, invenio_db/cli.py, invenio_db/ext.py, invenio_db/version.py, setup.py, tests/conftest.py
* Requires Flask>=0.11 and removes dependency on Flask-CLI.
* Adds missing deployment condition.
=> global: preparation for beta release

invenio_db/alembic/35c1075e6360_force_naming_convention.py, tests/test_db.py
* Adds warning when discovered CheckConstraint instead of raising
an exception.
=> alembic: warn on CheckConstraint

setup.cfg
- Ignores pydocstyle errors about first line imperative mood.
(addresses inveniosoftware/troubleshooting#9)
=> tests: pydocstyle ignore D401

CHANGES.rst, RELEASE-NOTES.rst, invenio_db/version.py
* Releases v1.0.0b5 just after v1.0.0b4 because pypi doesn't
allow to reupload files and v1.0.0b4 has been rollbacked.
Signed-off-by: Nicolas Harraudeau <nicolas.harraudeau@cern.ch>
=> release: v1.0.0b5

invenio_db/cli.py, invenio_db/utils.py, tests/test_db.py
- Fixes sequence bug in transaction table.
- Adds to the cli drop command the alembic_version table.
Addresses [#72](https://github.com/inveniosoftware/invenio-db/issues/72). 
=> cli: alembic_version table manual drop

invenio_db/alembic/dbdbc1b19cf2_create_transaction_table.py, invenio_db/cli.py, invenio_db/utils.py, setup.py, tests/test_db.py
- Fixes creation of sequence in transaction table,
to make it able to drop
- Adds a utility function to drop the alembic_version table
Closes [#83](https://github.com/inveniosoftware/invenio-db/issues/83)
=> wip alembic: fix in transaction recipe

invenio_db/ext.py
* Set SQLALCHEMY_ECHO=False as default value.
(closes inveniosoftware/invenio-app-ils#19)
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
=> ext: SQLALCHEMY_ECHO default switched off

invenio_db/ext.py, invenio_db/utils.py, tests/test_utils.py
* Checks for already registered models before building versioning
models. (closes #96)
=> global: avoid double versioned models registration

setup.py
Closes https://github.com/inveniosoftware/invenio-db/issues/101
=> installation: psycopg2 -> psycopg2-binary

setup.py
Pin SQLAlchemy-Continuum upper version limit (<1.3.5) to avoid crashing due to https://github.com/kvesteri/sqlalchemy-continuum/issues/188
=> Fix: Pin SQLAlchemy-Continuum

docs/index.rst, docs/session_management.rst, setup.py
=> docs: adds section about DB session management

.travis.yml, requirements-devel.txt, setup.py
=> travis: update python matrix

.gitignore, .travis.yml, invenio_db/alembic/dbdbc1b19cf2_create_transaction_table.py, invenio_db/utils.py, pytest.ini, run-tests.sh, setup.cfg, setup.py, tests/conftest.py, tests/demo/__init__.py, tests/demo/child.py, tests/demo/parent.py, tests/demo/versioned_a.py, tests/demo/versioned_b.py
Requires https://github.com/inveniosoftware/docker-services-cli/pull/10
=> tests: migrate to docker-services-cli + Postgres 12

invenio_db/cli.py
Turns out that `invenio db init` and `invenio db destroy` print out the full db url including sensitive information like the password on stdout. We want none of that.
=> security: hide sensitive info from output

setup.py
=> dependencies: cap sqlalchemy to <1.4.0

CHANGES.rst, invenio_db/version.py, setup.py
Flask-SQLAlchemy was released a couple hours ago and is breaking things. Until it's patched, we shouldn't depend on it.
=> cap flask-sqlalchemy below 2.5

invenio_db/ext.py, tests/test_db.py
DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
=> remove deprecation warning from importlib_metadata

invenio_db/ext.py, invenio_db/utils.py
* By default Alembic uses a single transaction for running all
migrations. This however makes it very hard to write migration scripts
that work on both PostgreSQL and MySQL.
=> alembic: one transaction per migration

.github/workflows/tests.yml, invenio_db/cli.py, invenio_db/proxies.py, invenio_db/utils.py, setup.cfg, tests/test_db.py, tests/test_utils.py, tests/test_versioning.py
- setup: increase flask-sqlalchemy version
- fix: tests LocalProxy
- change: remove click 3 compatibility
- change: add proxy file
NOTE: the [bugfix](https://github.com/inveniosoftware/invenio-db/pull/158/commits/c8024093606d9d37c19177c23aeaeb5a6f70ab49) has to be discussed before merging!
if we use the change then following two lines have to be updated:
[invenio_oauth2server.utils](https://github.com/inveniosoftware/invenio-oauth2server/blob/a66db442f7c2744f3b9f604523c5d67783231276/invenio_oauth2server/utils.py#L36)
[invenio_oauthclient.utils](https://github.com/inveniosoftware/invenio-oauthclient/blob/4a7a2d08b6d14ebf9509ad896375f709730fe0f6/invenio_oauthclient/utils.py#L307)
=> update flask sqlalchemy

invenio_db/ext.py
Here the [docs](https://alembic.sqlalchemy.org/en/latest/api/runtime.html#alembic.runtime.environment.EnvironmentContext.configure.params.compare_type) about compare_type
=> alembic: allow to compare type changes

invenio_db/alembic/35c1075e6360_force_naming_convention.py
:heart: Thank you for your contribution!
Please describe briefly your pull request.
Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license …
=> alembic: fix sqlalchemy op.execute() due to latest sqlalchamy-continuum

.github/workflows/tests.yml, invenio_db/services/uow.py
Add UnitOfWork from https://github.com/inveniosoftware/invenio-records-resources/blob/master/invenio_records_resources/services/uow.py to decouple from Records.
=> Add UnitOfWork

invenio_db/uow.py, tests/test_uow.py
- When an exception occurs and the unit of work is being rolled back, we
want to add the possibility to perform some clean-up actions that can
also be commited to the database.
- The new `on_exception` method is added because we want to keep
backwards compatibility and also introduce the same "triplet" of
methods as we have for the "happy path" (`on_register`, `on_commit`,
`on_post_commit`).
- Closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1861
=> uow: add "on_exception" lifecycle hook

.github/workflows/tests.yml, CHANGES.rst, invenio_db/__init__.py, invenio_db/alembic/dbdbc1b19cf2_create_transaction_table.py, invenio_db/cli.py, invenio_db/ext.py, invenio_db/proxies.py, invenio_db/uow.py, invenio_db/utils.py, setup.cfg, tests/conftest.py, tests/mocks.py, tests/test_db.py, tests/test_utils.py, tests/test_versioning.py
- setup: increase flask-sqlalchemy version
- fix: tests LocalProxy
- change: remove click 3 compatibility
- change: add proxy file
- fix: WeakKeyDictionary
- fix: remove warning and black problems
- fix: VARCHAR needs length on mysql
- fix: make variable names more distinguishable
- fix: comment assert in tests_db
- refactor: rename current_db to current_sqlalchemy
- setup: remove upper pins
- refactor: move MockEntryPoint to independent file
- tests: fix sqlalchemy.exc.InvalidRequestError
- tests: fix sqlalchemy.exc.InvalidRequestError
- cli: password is per default hided
- not finished commit
worked locally with flask>=3.0.0, werkzeug>=3.0.0, flask-alemib>=3.0.0. further updated invenio-base is necessary (otherwise flask and werkzeug couldn't be updated) 
tests are not independent. if …
=> remove upper limit
